
# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 数学渲染设置
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# 插件设置
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 排除文件
exclude:
  - README.md
  - LICENSE
  - .gitignore


# MathJax特定配置
mathjax:
  enable: true
  config_file: false
  process_escapes: true
  tex2jax:
    inlineMath: [ ['$','$'], ["\\(","\\)"] ]
    displayMath: [ ['$$','$$'], ["\\[","\\]"] ]
    processEscapes: true